language: java
sudo: false
jdk:
- openjdk7
before_install:
- python travis.py --mirrors
install:
- ./run_maven.sh none -DskipTests=true -B -V -q install
test:
- ./run_maven.sh none -B -q test
env:
  global:
  - CI_USER=$USER
