language: java
sudo: false
jdk:
- openjdk7
before_install:
- python travis.py --mirrors
install:
- ./run_maven.sh $MONASCA_COMMON_VERSION none -DskipTests=true -B -V -q install
test:
- ./run_maven.sh $MONASCA_COMMON_VERSION none -B -q test
env:
  global:
  - CI_USER=$USER
  - MONASCA_COMMON_VERSION=1.1.0
